VENDOR = Sanguino
ARDUINO_VERSION = 10612
#ARDUINO_DIR = ${HOME}/arduino-1.6.12
#ARDUINO_DIR = /usr/share/arduino
#ARDUINO_DIR = ${HOME}/.arduino15
ARDUINO_DIR = /home/pdbogen/arduino-1.8.1
ARDUINO_CORE_PATH = ${ARDUINO_DIR}/hardware/arduino/avr/cores/arduino
ALTERNATE_CORE_PATH = ${HOME}/.arduino15/packages/Sanguino/hardware/avr/1.0.2
BOARD_TAG = sanguino
BOARD_SUB = atmega1284p
ARDUINO_PORT = /dev/ttyUSB0
AVRDUDE_OPTS = -V
AVRDUDE_ARD_BAUDRATE = 57600

include /usr/share/arduino/Arduino.mk
